[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "d1_1"
path = "src/d1_1.rs"

[[bin]]
name = "d1_2"
path = "src/d1_2.rs"

[[bin]]
name = "d2_1"
path = "src/d2_1.rs"

[[bin]]
name = "d2_2"
path = "src/d2_2.rs"

[dependencies]
